version: 0.1

phases:
  build:
    commands:
      - npm install
      - npm run build
artifacts:
  files:
    - dist/index.html
    - dist/main.bundle.js
    - dist/vendors~main.bundle.js
  discard-paths: yes
